version: 2
updates:
  - package-ecosystem: "npm"
    directory: "nav-app"
    schedule:
      interval: "quarterly"
    target-branch: "develop"

    groups:
      angular-ecosystem:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "@angular-builders/*"
          - "rxjs"
          - "typescript"
          - "ngx-markdown"
          - "marked" # peer of ngx-markdown, must update together
          - "ngx-drag-drop"
          - "ngx-color-picker"
        update-types:
          - "minor"
          - "patch"

    ignore:
      - dependency-name: "@angular/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular-devkit/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular-builders/*"
        update-types: ["version-update:semver-major"]
      # libraries constrained by angular version
      - dependency-name: "rxjs"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "ngx-*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "marked"
        update-types: ["version-update:semver-major"]
